version: "2"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - POSTGRESQL__DSN=postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__BAND__NAME=${NETWORK_SERVER__BAND__NAME:-EU868}
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://mosquitto:1883
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
    depends_on:
      - postgresql
      - mosquitto

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - POSTGRESQL__DSN=postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-application-server:8001
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=verysecret
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://mosquitto:1883
      - BACKEND__TYPE=basic_station
      - BACKEND__BASIC_STATION__BIND=:3001
      - BACKEND__BASIC_STATION__REGION=US915
      - BACKEND__BASIC_STATION__CA_CERT="-----BEGIN CERTIFICATE-----MIIDSDCCAjCgAwIBAgIUBvmUGD55aEspmlECBS2TODBCWT4wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UEAwwKY2hpcnBzdGFjazAeFw0yMzA2MTIxNjEyMTNaFw0zMzA2MDkxNjEyMTNaMBUxEzARBgNVBAMMCmNoaXJwc3RhY2swggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBr6j+xOSYaHu2dJs/TcOx1O0uYjw4l/aCAp8lmiXOeqxj5DS6MheXO/iqSkJCicHWPfc+j7YRhE+63w4BKdavWjtNchNmF8NZ//gP6Y5ZoIydvFcmE0xU4ZFYBTsW05Wjz8rTwiq2Yt92RmFQnKEVsqIYNvCgsOYGbaHrWn90SWAItxMUfxM6to44g3b3Th6qNT8xTH/yRbsnUtuZ1kqEw7cH2Ngs1B917pb08hvK+qwGJKxdjQI66za5X9/87hQw9nvKLO5qDv3svC2mgG8JqWB/buME4lBKHV6J8y56E6NQ0sbjbUTP82NR7bqLWoZtiudrZDLqGxjRlwUBSyNTAgMBAAGjgY8wgYwwHQYDVR0OBBYEFDBgPV6khcJcZAXe5Tom8iMOnfCpMFAGA1UdIwRJMEeAFDBgPV6khcJcZAXe5Tom8iMOnfCpoRmkFzAVMRMwEQYDVQQDDApjaGlycHN0YWNrghQG+ZQYPnloSymaUQIFLZM4MEJZPjAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEAD361rsoAKPx6Y/Ib6tUudaXIjoRJXMy5P4s43LoYvpvBwCVqQecrGfmr9K7gQd0qKa+dbcqODVJUjdbYWNlA0HUDPnsHYGxWsUMmrFmdktJCEuOhgezYTnbcETZWzJ+cJsnT2dkBHVO/waViOxm7w+9pwduY+kLx5R5PprayDe30ynjBhoWE7MxshrRLAmDCpncVuuSBhTDj/JCwMX5AyYeae53UcsQZD4EF3P+NJ64HVd4nd/j42WBTSfdInuzsL2v6VqWFmWiCYSSxKYVwHMuYEQnOcY1WRv+uQgGIJxKuGRmVi1g/qH7X0jJMXWRp0CtjYHbL1dNlciJ/UOnptA==-----END CERTIFICATE-----"
      - BACKEND__BASIC_STATION__FREQUENCY_MIN=902000000
      - BACKEND__BASIC_STATION__FREQUENCY_MAX=928000000
    depends_on: 
      - mosquitto

  postgresql:
    #image: sheng2216/postgres_for_chirpstack:rak
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: unless-stopped
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    ports:
      - 1883:1883

volumes:
  postgresqldata:
  redisdata:
