version: '3'

services:
  rak7391-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - CHIRPSTACK_HOST=${CHIRPSTACK_HOST:-127.0.0.1:8000}
      - CHIRPSTACK_AUTH_USERNAME=${CHIRPSTACK_AUTH_USERNAME:-admin}
      - CHIRPSTACK_AUTH_PASSWORD=${CHIRPSTACK_AUTH_PASSWORD:-admin}

      - DATABASE_NAME = ${DATABASE_NAME:-teapotlabs.db}

      - LORAWAN_NETWORK_HOST=${LORAWAN_NETWORK_HOST:-127.0.0.1}
      - LORAWAN_NETWORK_PORT=${LORAWAN_NETWORK_PORT:-1883}
      - LORAWAN_NETWORK_TOPIC=${LORAWAN_NETWORK_TOPIC:-application/+/device/+/rx}

      - EXTERNAL_NETWORK_TYPE=${EXTERNAL_NETWORK_TYPE:-mqtt}
      - EXTERNAL_NETWORK_HOST=${EXTERNAL_NETWORK_HOST:-127.0.0.1}
      - EXTERNAL_NETWORK_PORT=${EXTERNAL_NETWORK_PORT:-1883}
      - EXTERNAL_NETWORK_TOPIC_DATA_OUT=${EXTERNAL_NETWORK_TOPIC_DATA_OUT:-application/+/device/+/tx}
      - EXTERNAL_NETWORK_TOPIC_DATA_IN=${EXTERNAL_NETWORK_TOPIC_DATA_IN:-application/+/device/+/rx}
      - EXTERNAL_NETWORK_ROOT_CERT=${EXTERNAL_NETWORK_ROOT_CERT:-/BEGIN ROOT CERT/}
      - EXTERNAL_NETWORK_CERTIFICATE=${EXTERNAL_NETWORK_CERTIFICATE:-/BEGIN CERT/}
      - EXTERNAL_NETWORK_PRIVATE_KEY=${EXTERNAL_NETWORK_PRIVATE_KEY:-/BEGIN PRIVATE KEY/}
      
      - EXTERNAL_NETWORK_SERIALPORT=${EXTERNAL_NETWORK_SERIALPORT:-/dev/ttyUSB0}
      - EXTERNAL_NETWORK_BAUDRATE=${EXTERNAL_NETWORK_BAUDRATE:-115200}

      - SEND_STORED_DEVICE_MESSAGE_DELAY = ${SEND_STORED_DEVICE_MESSAGE_DELAY:-50}
